version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: hbsolution-postgres-1
    environment:
      POSTGRES_DB: HBsolution
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
