version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hbsolution-mysql-1
    environment:
      MYSQL_DATABASE: HBsolution
      MYSQL_USER: hbsolutionadmin
      MYSQL_PASSWORD: Berlolo@0106
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hbsolution-backend-1
    ports:
      - "8080:8080"
      - "5005:5005" # porta do debug
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/HBsolution?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: hbsolutionadmin
      SPRING_DATASOURCE_PASSWORD: Berlolo@0106
      JWT_SECRET: "S3nh@UltraS3gur@!2025_AplicacaoHbSolution"
      JWT_EXPIRATION: 86400000
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

volumes:
  mysql_data:
