version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hbsolution-backend
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/HBsolution?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: hbsolutionadmin
      SPRING_DATASOURCE_PASSWORD: Berlolo@0106
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      JWT_SECRET: "S3nh@UltraS3gur@!2025_AplicacaoHbSolution"
      JWT_EXPIRATION: 86400000
    restart: always
