# --- Aplicação ---
spring.application.name=HbSolution
server.servlet.context-path=/api
server.port=8080

# URL base do Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


# --- Banco de dados (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://postgres:5432/HBsolution
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hbsolutionadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Berlolo@0106}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.packages-to-scan=com.api.HbSolution.entity
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Log SQL ---
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# --- JWT ---
jwt.secret=${JWT_SECRET:defaultSecretKey}
jwt.expiration=${JWT_EXPIRATION:86400000}
